### ISSUE TITLE
Agregar datos en la sección "Nosotros".

### ISSUE THREAD

**Issue by JoaquinFranich** [chachoariel/devtech-podcast-web#3]
Hola, Ariel.

Voy a agregar mis datos en la segunda tarjeta de la sección "Nosotros".

Saludos!

**Comment by JoaquinFranich** [comment]
Hola, Ariel.

Voy a agregar mis datos en la segunda tarjeta de la seccion "Nosotros".

Saludos!

**Comment by chachoariel** [comment]
ok muchas gracias por colaborar
